"use client";

export default function Head() {
	return (
		<>
			<title>@grafisaholic</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/gr-icon.ico" />
		</>
	);
}
